actuators:
  - package: dynamixel_x_controller
    class: Dynamixel_X::Dynamixel_X_Actuator_Config_Parser
    config:
      dynx_1:
        servo_id: 7
        controller_name: dynx_controller
        zero_deg: 0.0
        cw_limit_deg: 0.0
        ccw_limit_deg: 360.0

controllers:
  - package: dynamixel_x_controller
    class: Dynamixel_X::Dynamixel_X_Controller_Config_Parser
    config:
      dynx_controller:
        controller_id: 1
        port: /dev/u2d2
        baud_rate: 57600
